name: Build_And_Deploy_To_Firebase

on:
  push:
    branches:
    - master

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Decrypt large secret
      run: ./.github/scripts/decrypt_secret.sh
      env:
        GPG_SECRETS: ${{ secrets.GPG_SECRETS }}
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm install -g @angular/cli
    - run: npm install --prefix functions
    - run: ng build --prod
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --project tonyloveshan-com-58a99
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        GOOGLE_APPLICATION_CREDENTIALS: ./secrets/service_account_key.json